# @package __global__

defaults:
  - watermark/default
  - /augmentations/default
  - /model: watermark/default
  - _self_

solver: watermarking # standard name to load the solver using builders
sample_rate: 16000
channels: 1

# metrics
metrics:
  visqol:
    mode: audio
    bin: null # path to visqol install
    model: tcdaudio14_aacvopus_coresv_svrnsim_n.68_g.01_c1.model # visqol v3

# data hyperparameters
dataset:
  batch_size: 16
  num_workers: 10
  segment_duration: 1
  sample_on_weight: false  # Uniform sampling all the way
  sample_on_duration: false  # Uniform sampling all the way

  train:
    num_samples: 50
  generate:
    batch_size: 16
    num_samples: 50
    segment_duration: 30
  valid:
    num_samples: 50

# solver hyperparameters
evaluate:
  every: 10
  num_workers: 5
  metrics:
    visqol: false
    sisnr: true
generate:
  every: 10
  num_workers: 5
  audio:
    sample_rate: ${sample_rate}

# checkpointing schedule
checkpoint:
  save_last: true
  save_every: 25
  keep_last: 10
  keep_every_states: null



# optimization hyperparameters
optim:
  epochs: 2
  updates_per_epoch: 10
  lr: 5e-5
  max_norm: 3.0
  optimizer: adam
  adam:
    betas: [0.5, 0.9]
    weight_decay: 0.
  ema:
    use: true # whether to use EMA or not
    updates: 1 # update at every step
    device: ${device} # device for EMA, can be put on GPU if more frequent updates
    decay: 0.99 # EMA decay value, if null, no EMA is used

  
schedule:
  lr_scheduler: "cosine"
  cosine:
    warmup: 4000
    lr_min_ratio: 0.0
    cycle_length: 1.0
